### ISSUE TITLE
Change in the return in /categories endpoint of the public-apis API

### ISSUE THREAD

**Issue by matheusfelipeog** [Free-APIs/Free-APIs.github.io#2]
Hi, I'm the maintainer of the public-apis project.

We recently made a change in the return of the `/categories` endpoint of our API to add a count key that contains the number of categories currently available in the project. This change caused unwanted behavior in Free APIs website when we tried to explore categories. I recommend that you update [this page](https://github.com/Free-APIs/Free-APIs.github.io/blob/main/src/pages/Categories/index.js) to make it fit and work properly.

Thanks for keeping this project <3

You can see more about the change at: https://github.com/davemachado/public-api/issues/29

**Comment by Free-APIs** [comment]
Thanks for the update! I've accordingly adjusted the endpoint used.
