### ISSUE TITLE
Regarding the current situation of the Public APIs project

### ISSUE THREAD

**Issue by pawelborkar** [Free-APIs/Free-APIs.github.io#4]
Hello There,
Hope your doing good. This issue is regarding the current situation which we the collaborators at [Public APIs](https://github.com/public-apis/public-apis/issues/3104) are facing  regarding the future of public apis and the open source community in general.

As we've added your website in one of the unofficial list of websites in the readme, there's a possibility of a number of people visiting it. So it's one of the reasons I'm writing this issue. In order to bring this issue in front of the community members  

Please read [this](https://github.com/public-apis/public-apis/issues/3104) issue and we would encourage you to spread it on your website's homepage or write blogs or a tweet about it in order to bring this serious issue into the limelight of the community members. And help the project to survive.

Thanks, 
Pawel

**Comment by Free-APIs** [comment]
Hey @pawelborkar,
I've accordingly updated the homepage to reflect the situation.
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/86627893/159044752-68c9cb22-5508-4fb7-9138-cdd89094093f.png">
I hope this resolves successfully for your team, and keep me updated if there are any changes!

**Comment by matheusfelipeog** [comment]
Thanks for the support @Free-APIs 

We will keep you updated.
